vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        documents:
            uri_prefix: /documents
            upload_destination: '%kernel.project_dir%/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
